/**
 * Expo config plugin: give the Android `release` build type a real signing
 * configuration instead of the debug keystore.
 *
 * WHY THIS EXISTS. Expo's prebuild template ships this, verbatim:
 *
 *     release {
 *         // Caution! In production, you need to generate your own keystore file.
 *         signingConfig signingConfigs.debug
 *     }
 *
 * A release AAB signed with the debug key is REJECTED by the Google Play
 * Console ("You uploaded an APK or Android App Bundle that was signed in
 * debug mode"). Found during the V1 production-readiness audit -- the
 * release build succeeded locally, so nothing surfaced it until the
 * signing configuration was actually read.
 *
 * WHY A PLUGIN AND NOT AN EDIT. mobile/android/ is generated by
 * `expo prebuild` and is gitignored; `prebuild --clean` recreates it from
 * the template every time. Any hand-edit to android/app/build.gradle is
 * therefore silently discarded on the next prebuild -- exactly the kind of
 * fix that appears to work and then vanishes. A config plugin is applied on
 * every prebuild, so the change is durable and reviewable in version
 * control. This is the standard approach for a Continuous Native Generation
 * project.
 *
 * NO CREDENTIALS LIVE HERE, OR ANYWHERE IN THIS REPOSITORY. The generated
 * Gradle code reads four Gradle properties, which belong in the developer's
 * OWN `~/.gradle/gradle.properties` (outside the repo, never committed):
 *
 *     BETHANIYA_UPLOAD_STORE_FILE=/absolute/path/to/upload-keystore.jks
 *     BETHANIYA_UPLOAD_STORE_PASSWORD=...
 *     BETHANIYA_UPLOAD_KEY_ALIAS=upload
 *     BETHANIYA_UPLOAD_KEY_PASSWORD=...
 *
 * FALLBACK BEHAVIOUR IS DELIBERATE. When those properties are absent the
 * release build keeps using the debug keystore, exactly as before. That
 * keeps `assembleRelease` working for local smoke-testing and on any
 * machine without the upload key, while a machine that HAS the key signs
 * properly and produces an uploadable bundle. The build logs which path it
 * took, so a debug-signed release is never a silent surprise.
 *
 * VERIFY after building:
 *     unzip -p app-release.aab META-INF/*.RSA | keytool -printcert
 * A debug-signed artifact shows CN=Android Debug.
 */
const { withAppBuildGradle } = require('expo/config-plugins');

/** Gradle snippet defining the upload signing config, inserted into the
 * existing `signingConfigs { ... }` block next to `debug`. */
const RELEASE_SIGNING_CONFIG = `
        release {
            // Populated from ~/.gradle/gradle.properties -- see
            // mobile/plugins/withReleaseSigning.js. Never from this repo.
            if (project.hasProperty('BETHANIYA_UPLOAD_STORE_FILE')) {
                storeFile file(BETHANIYA_UPLOAD_STORE_FILE)
                storePassword BETHANIYA_UPLOAD_STORE_PASSWORD
                keyAlias BETHANIYA_UPLOAD_KEY_ALIAS
                keyPassword BETHANIYA_UPLOAD_KEY_PASSWORD
            }
        }`;

/** Replaces the template's `signingConfig signingConfigs.debug` inside the
 * release build type with a conditional choice. */
const RELEASE_SIGNING_SELECTION = `signingConfig project.hasProperty('BETHANIYA_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug
            if (!project.hasProperty('BETHANIYA_UPLOAD_STORE_FILE')) {
                logger.warn('[withReleaseSigning] BETHANIYA_UPLOAD_STORE_FILE is not set -- ' +
                    'the release build is being signed with the DEBUG keystore. ' +
                    'Google Play will reject this artifact. See mobile/plugins/withReleaseSigning.js.')
            }`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error(
        'withReleaseSigning: expected a Groovy app/build.gradle; got ' +
          gradleConfig.modResults.language
      );
    }

    let contents = gradleConfig.modResults.contents;

    // Idempotence: prebuild may apply plugins more than once, and applying
    // this twice would define signingConfigs.release twice (a Gradle error).
    if (contents.includes('BETHANIYA_UPLOAD_STORE_FILE')) {
      return gradleConfig;
    }

    // 1. Add the `release` signing config beside the template's `debug` one.
    const debugSigningBlock = `        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }`;
    if (!contents.includes(debugSigningBlock)) {
      throw new Error(
        'withReleaseSigning: could not find the expected debug signingConfig block in ' +
          'app/build.gradle. The Expo template changed -- update this plugin rather ' +
          'than shipping a debug-signed release.'
      );
    }
    contents = contents.replace(
      debugSigningBlock,
      debugSigningBlock + RELEASE_SIGNING_CONFIG
    );

    // 2. Point the release build type at it. The template has exactly one
    //    occurrence inside buildTypes.release, immediately after a comment
    //    warning about this very problem.
    const templateReleaseSigning = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;
    if (!contents.includes(templateReleaseSigning)) {
      throw new Error(
        'withReleaseSigning: could not find the release build type’s debug ' +
          'signingConfig line in app/build.gradle. The Expo template changed -- ' +
          'update this plugin rather than shipping a debug-signed release.'
      );
    }
    contents = contents.replace(
      templateReleaseSigning,
      `            ${RELEASE_SIGNING_SELECTION}`
    );

    gradleConfig.modResults.contents = contents;
    return gradleConfig;
  });
};
