/**
 * The 66-book Protestant Bible canon -- structural metadata only (id,
 * name, testament, canonical order, chapter count). This is NOT
 * scripture text and is not subject to /BIBLE_LICENSING.md's
 * restrictions: book names and chapter counts are objective, universally
 * published facts about a translation-independent canon structure, not
 * copyrightable expression -- see types.ts's doc comment. Chapter counts
 * below sum to 929 (OT) + 260 (NT) = 1189, the well-known total chapter
 * count for this canon; books.test.ts checks this as a data-integrity
 * guard.
 *
 * TELUGU BOOK NAMES (`nameTe`) were added during the V1 tester-feedback
 * pass. Source: https://github.com/aruljohn/Bible-telugu `Books.json`
 * (MIT, Copyright (c) 2021 Arul John) -- a named, checkable source with
 * explicit english/telugu pairs for all 66 books, fetched via a direct
 * HTTPS request, NOT transliterated or generated by any AI tool. The one
 * naming variance is handled explicitly: that source titles the book
 * "Song of Songs" where this file uses the equally standard "Song of
 * Solomon" -- the same book under its two standard English titles. See
 * /BIBLE_LICENSING.md for the full provenance writeup.
 *
 * Still structural metadata, not scripture text: these are the book
 * names a Telugu Bible prints in its table of contents, not translated
 * verses.
 */
import type { BibleBook, BibleLanguage } from './types';

export const OLD_TESTAMENT_BOOKS: BibleBook[] = [
  {
    id: 'genesis',
    name: 'Genesis',
    nameTe: 'ఆదికాండము',
    testament: 'OT',
    order: 1,
    chapterCount: 50,
  },
  {
    id: 'exodus',
    name: 'Exodus',
    nameTe: 'నిర్గమకాండము',
    testament: 'OT',
    order: 2,
    chapterCount: 40,
  },
  {
    id: 'leviticus',
    name: 'Leviticus',
    nameTe: 'లేవీయకాండము',
    testament: 'OT',
    order: 3,
    chapterCount: 27,
  },
  {
    id: 'numbers',
    name: 'Numbers',
    nameTe: 'సంఖ్యాకాండము',
    testament: 'OT',
    order: 4,
    chapterCount: 36,
  },
  {
    id: 'deuteronomy',
    name: 'Deuteronomy',
    nameTe: 'ద్వితీయోపదేశకాండమ',
    testament: 'OT',
    order: 5,
    chapterCount: 34,
  },
  {
    id: 'joshua',
    name: 'Joshua',
    nameTe: 'యెహొషువ',
    testament: 'OT',
    order: 6,
    chapterCount: 24,
  },
  {
    id: 'judges',
    name: 'Judges',
    nameTe: 'న్యాయాధిపతులు',
    testament: 'OT',
    order: 7,
    chapterCount: 21,
  },
  {
    id: 'ruth',
    name: 'Ruth',
    nameTe: 'రూతు',
    testament: 'OT',
    order: 8,
    chapterCount: 4,
  },
  {
    id: '1-samuel',
    name: '1 Samuel',
    nameTe: 'సమూయేలు మొదటి గ్రంథము',
    testament: 'OT',
    order: 9,
    chapterCount: 31,
  },
  {
    id: '2-samuel',
    name: '2 Samuel',
    nameTe: 'సమూయేలు రెండవ గ్రంథము',
    testament: 'OT',
    order: 10,
    chapterCount: 24,
  },
  {
    id: '1-kings',
    name: '1 Kings',
    nameTe: 'రాజులు మొదటి గ్రంథము',
    testament: 'OT',
    order: 11,
    chapterCount: 22,
  },
  {
    id: '2-kings',
    name: '2 Kings',
    nameTe: 'రాజులు రెండవ గ్రంథము',
    testament: 'OT',
    order: 12,
    chapterCount: 25,
  },
  {
    id: '1-chronicles',
    name: '1 Chronicles',
    nameTe: 'దినవృత్తాంతములు మొదటి గ్రంథము',
    testament: 'OT',
    order: 13,
    chapterCount: 29,
  },
  {
    id: '2-chronicles',
    name: '2 Chronicles',
    nameTe: 'దినవృత్తాంతములు రెండవ గ్రంథము',
    testament: 'OT',
    order: 14,
    chapterCount: 36,
  },
  {
    id: 'ezra',
    name: 'Ezra',
    nameTe: 'ఎజ్రా',
    testament: 'OT',
    order: 15,
    chapterCount: 10,
  },
  {
    id: 'nehemiah',
    name: 'Nehemiah',
    nameTe: 'నెహెమ్యా',
    testament: 'OT',
    order: 16,
    chapterCount: 13,
  },
  {
    id: 'esther',
    name: 'Esther',
    nameTe: 'ఎస్తేరు',
    testament: 'OT',
    order: 17,
    chapterCount: 10,
  },
  {
    id: 'job',
    name: 'Job',
    nameTe: 'యోబు గ్రంథము',
    testament: 'OT',
    order: 18,
    chapterCount: 42,
  },
  {
    id: 'psalms',
    name: 'Psalms',
    nameTe: 'కీర్తనల గ్రంథము',
    testament: 'OT',
    order: 19,
    chapterCount: 150,
  },
  {
    id: 'proverbs',
    name: 'Proverbs',
    nameTe: 'సామెతలు',
    testament: 'OT',
    order: 20,
    chapterCount: 31,
  },
  {
    id: 'ecclesiastes',
    name: 'Ecclesiastes',
    nameTe: 'ప్రసంగి',
    testament: 'OT',
    order: 21,
    chapterCount: 12,
  },
  {
    id: 'song-of-solomon',
    name: 'Song of Solomon',
    nameTe: 'పరమగీతము',
    testament: 'OT',
    order: 22,
    chapterCount: 8,
  },
  {
    id: 'isaiah',
    name: 'Isaiah',
    nameTe: 'యెషయా గ్రంథము',
    testament: 'OT',
    order: 23,
    chapterCount: 66,
  },
  {
    id: 'jeremiah',
    name: 'Jeremiah',
    nameTe: 'యిర్మీయా',
    testament: 'OT',
    order: 24,
    chapterCount: 52,
  },
  {
    id: 'lamentations',
    name: 'Lamentations',
    nameTe: 'విలాపవాక్యములు',
    testament: 'OT',
    order: 25,
    chapterCount: 5,
  },
  {
    id: 'ezekiel',
    name: 'Ezekiel',
    nameTe: 'యెహెజ్కేలు',
    testament: 'OT',
    order: 26,
    chapterCount: 48,
  },
  {
    id: 'daniel',
    name: 'Daniel',
    nameTe: 'దానియేలు',
    testament: 'OT',
    order: 27,
    chapterCount: 12,
  },
  {
    id: 'hosea',
    name: 'Hosea',
    nameTe: 'హొషేయ',
    testament: 'OT',
    order: 28,
    chapterCount: 14,
  },
  {
    id: 'joel',
    name: 'Joel',
    nameTe: 'యోవేలు',
    testament: 'OT',
    order: 29,
    chapterCount: 3,
  },
  {
    id: 'amos',
    name: 'Amos',
    nameTe: 'ఆమోసు',
    testament: 'OT',
    order: 30,
    chapterCount: 9,
  },
  {
    id: 'obadiah',
    name: 'Obadiah',
    nameTe: 'ఓబద్యా',
    testament: 'OT',
    order: 31,
    chapterCount: 1,
  },
  {
    id: 'jonah',
    name: 'Jonah',
    nameTe: 'యోనా',
    testament: 'OT',
    order: 32,
    chapterCount: 4,
  },
  {
    id: 'micah',
    name: 'Micah',
    nameTe: 'మీకా',
    testament: 'OT',
    order: 33,
    chapterCount: 7,
  },
  {
    id: 'nahum',
    name: 'Nahum',
    nameTe: 'నహూము',
    testament: 'OT',
    order: 34,
    chapterCount: 3,
  },
  {
    id: 'habakkuk',
    name: 'Habakkuk',
    nameTe: 'హబక్కూకు',
    testament: 'OT',
    order: 35,
    chapterCount: 3,
  },
  {
    id: 'zephaniah',
    name: 'Zephaniah',
    nameTe: 'జెఫన్యా',
    testament: 'OT',
    order: 36,
    chapterCount: 3,
  },
  {
    id: 'haggai',
    name: 'Haggai',
    nameTe: 'హగ్గయి',
    testament: 'OT',
    order: 37,
    chapterCount: 2,
  },
  {
    id: 'zechariah',
    name: 'Zechariah',
    nameTe: 'జెకర్యా',
    testament: 'OT',
    order: 38,
    chapterCount: 14,
  },
  {
    id: 'malachi',
    name: 'Malachi',
    nameTe: 'మలాకీ',
    testament: 'OT',
    order: 39,
    chapterCount: 4,
  },
];

export const NEW_TESTAMENT_BOOKS: BibleBook[] = [
  {
    id: 'matthew',
    name: 'Matthew',
    nameTe: 'మత్తయి సువార్త',
    testament: 'NT',
    order: 40,
    chapterCount: 28,
  },
  {
    id: 'mark',
    name: 'Mark',
    nameTe: 'మార్కు సువార్త',
    testament: 'NT',
    order: 41,
    chapterCount: 16,
  },
  {
    id: 'luke',
    name: 'Luke',
    nameTe: 'లూకా సువార్త',
    testament: 'NT',
    order: 42,
    chapterCount: 24,
  },
  {
    id: 'john',
    name: 'John',
    nameTe: 'యోహాను సువార్త',
    testament: 'NT',
    order: 43,
    chapterCount: 21,
  },
  {
    id: 'acts',
    name: 'Acts',
    nameTe: 'అపొస్తలుల కార్యములు',
    testament: 'NT',
    order: 44,
    chapterCount: 28,
  },
  {
    id: 'romans',
    name: 'Romans',
    nameTe: 'రోమీయులకు',
    testament: 'NT',
    order: 45,
    chapterCount: 16,
  },
  {
    id: '1-corinthians',
    name: '1 Corinthians',
    nameTe: '1 కొరింథీయులకు',
    testament: 'NT',
    order: 46,
    chapterCount: 16,
  },
  {
    id: '2-corinthians',
    name: '2 Corinthians',
    nameTe: '2 కొరింథీయులకు',
    testament: 'NT',
    order: 47,
    chapterCount: 13,
  },
  {
    id: 'galatians',
    name: 'Galatians',
    nameTe: 'గలతీయులకు',
    testament: 'NT',
    order: 48,
    chapterCount: 6,
  },
  {
    id: 'ephesians',
    name: 'Ephesians',
    nameTe: 'ఎఫెసీయులకు',
    testament: 'NT',
    order: 49,
    chapterCount: 6,
  },
  {
    id: 'philippians',
    name: 'Philippians',
    nameTe: 'ఫిలిప్పీయులకు',
    testament: 'NT',
    order: 50,
    chapterCount: 4,
  },
  {
    id: 'colossians',
    name: 'Colossians',
    nameTe: 'కొలొస్సయులకు',
    testament: 'NT',
    order: 51,
    chapterCount: 4,
  },
  {
    id: '1-thessalonians',
    name: '1 Thessalonians',
    nameTe: '1 థెస్సలొనీకయులకు',
    testament: 'NT',
    order: 52,
    chapterCount: 5,
  },
  {
    id: '2-thessalonians',
    name: '2 Thessalonians',
    nameTe: '2 థెస్సలొనీకయులకు',
    testament: 'NT',
    order: 53,
    chapterCount: 3,
  },
  {
    id: '1-timothy',
    name: '1 Timothy',
    nameTe: '1 తిమోతికి',
    testament: 'NT',
    order: 54,
    chapterCount: 6,
  },
  {
    id: '2-timothy',
    name: '2 Timothy',
    nameTe: '2 తిమోతికి',
    testament: 'NT',
    order: 55,
    chapterCount: 4,
  },
  {
    id: 'titus',
    name: 'Titus',
    nameTe: 'తీతుకు',
    testament: 'NT',
    order: 56,
    chapterCount: 3,
  },
  {
    id: 'philemon',
    name: 'Philemon',
    nameTe: 'ఫిలేమోనుకు',
    testament: 'NT',
    order: 57,
    chapterCount: 1,
  },
  {
    id: 'hebrews',
    name: 'Hebrews',
    nameTe: 'హెబ్రీయులకు',
    testament: 'NT',
    order: 58,
    chapterCount: 13,
  },
  {
    id: 'james',
    name: 'James',
    nameTe: 'యాకోబు',
    testament: 'NT',
    order: 59,
    chapterCount: 5,
  },
  {
    id: '1-peter',
    name: '1 Peter',
    nameTe: '1 పేతురు',
    testament: 'NT',
    order: 60,
    chapterCount: 5,
  },
  {
    id: '2-peter',
    name: '2 Peter',
    nameTe: '2 పేతురు',
    testament: 'NT',
    order: 61,
    chapterCount: 3,
  },
  {
    id: '1-john',
    name: '1 John',
    nameTe: '1 యోహాను',
    testament: 'NT',
    order: 62,
    chapterCount: 5,
  },
  {
    id: '2-john',
    name: '2 John',
    nameTe: '2 యోహాను',
    testament: 'NT',
    order: 63,
    chapterCount: 1,
  },
  {
    id: '3-john',
    name: '3 John',
    nameTe: '3 యోహాను',
    testament: 'NT',
    order: 64,
    chapterCount: 1,
  },
  {
    id: 'jude',
    name: 'Jude',
    nameTe: 'యూదా',
    testament: 'NT',
    order: 65,
    chapterCount: 1,
  },
  {
    id: 'revelation',
    name: 'Revelation',
    nameTe: 'ప్రకటన గ్రంథము',
    testament: 'NT',
    order: 66,
    chapterCount: 22,
  },
];

export const BIBLE_BOOKS: BibleBook[] = [...OLD_TESTAMENT_BOOKS, ...NEW_TESTAMENT_BOOKS];

const BOOKS_BY_ID = new Map(BIBLE_BOOKS.map((book) => [book.id, book]));

export function getBookById(bookId: string): BibleBook | undefined {
  return BOOKS_BY_ID.get(bookId);
}

/**
 * The book's display name in the caller's Bible language -- the single
 * accessor every screen and navigator title goes through.
 *
 * Every user-facing book name must come from here. Reading `book.name`
 * directly is the bug this replaces: BooksListScreen and
 * ChaptersListScreen did exactly that and so always showed English, even
 * with the Telugu Bible selected and Telugu verse text rendering
 * underneath.
 */
export function getBookName(book: BibleBook, language: BibleLanguage): string {
  return language === 'te' ? book.nameTe : book.name;
}

/** Convenience for the callers that only hold an id (navigator titles). */
export function getBookNameById(
  bookId: string,
  language: BibleLanguage
): string | undefined {
  const book = BOOKS_BY_ID.get(bookId);
  return book ? getBookName(book, language) : undefined;
}
