/**
 * The bundled Telugu Bible: Indian Revised Version (IRV) 2019.
 *
 * ---------------------------------------------------------------------
 * SOURCE AND LICENCE
 * ---------------------------------------------------------------------
 *   Text     ఇండియన్ రివైజ్డ్ వెర్షన్ (IRV) - తెలుగు -2019
 *   Source   BibleNLP/ebible, corpus/tel-tel2017.txt, line-aligned to
 *            metadata/vref.txt. Fetched verbatim over HTTPS from
 *            raw.githubusercontent.com; not regenerated by any tool.
 *   Licence  CC BY-SA 4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
 *   Holder   © 2017, 2019 Bridge Connectivity Solutions
 *
 * The attribution this licence requires is shown in the app's Settings
 * screen. See /BIBLE_LICENSING.md for the full writeup, and
 * scripts/import-telugu-bible.mjs for the import -- which re-reads the
 * upstream `metadata/licences.tsv` row on every run and refuses to import
 * if the terms have changed.
 *
 * ---------------------------------------------------------------------
 * WHAT V1 GOT WRONG, AND WHY THE SHAPE CHANGED
 * ---------------------------------------------------------------------
 * V1 read `./data/web-te.json`, produced by an import that kept only the
 * source lines carrying text and silently discarded the other two states
 * the source marks. Its doc comment claimed the result had been
 * "confirmed by cross-checking every chapter's verse-number set" to have
 * "no true mid-chapter holes, only combined numbering at the high end".
 * That verification was mistaken: Luke 1 alone had holes at verses 40,
 * 49, 55, 71, 72, 73, 75, 77 and 78 -- squarely mid-chapter.
 *
 * The two discarded states:
 *
 *   `<range>`   100 verses. The verse belongs to a MERGED range whose
 *               text sits on the range's first verse. Dropping the marker
 *               made verse numbers skip, so a reader saw 39 then 41 and
 *               reasonably concluded scripture was missing. It never was.
 *
 *   (empty)     202 slots. The verse does not exist in this translation's
 *               versification, because the IRV follows Hebrew/Masoretic
 *               chapter division for some passages.
 *
 * `./data/irv-te.json` preserves both. Each chapter is an array of spans
 * `[startVerse, endVerse, text]`, where `endVerse` exceeds `startVerse`
 * only for a merged range, and a verse number covered by no span is
 * genuinely absent from this translation rather than quietly replaced by
 * the next verse along.
 *
 * Keyed `[bookOrder][chapterNumber]`, where bookOrder matches books.ts's
 * `order` field exactly (1 = Genesis … 66 = Revelation). Book NAMES are
 * never keys -- see books.ts.
 */
import teluguData from './data/irv-te.json';
import type { BibleVerse } from './types';
import type { VerseSpan } from './alignment';

/** `[startVerse, endVerse, text]` -- see this module's doc comment. */
type RawSpan = [number, number, string];
type TeluguBibleData = Record<string, Record<string, RawSpan[]>>;

const DATA = teluguData as unknown as TeluguBibleData;

function rawSpansFor(bookOrder: number, chapterNumber: number): RawSpan[] | undefined {
  const spans = DATA[String(bookOrder)]?.[String(chapterNumber)];
  return spans && spans.length > 0 ? spans : undefined;
}

/**
 * The chapter's translated units, with merged ranges intact -- what the
 * bilingual reader needs in order to pair safely.
 *
 * Returns undefined when this translation has no text for the chapter at
 * all. Exactly one canonical chapter is in that state: Malachi 4, whose
 * Hebrew-numbered slots are empty upstream.
 */
export function getTeluguSpans(
  bookOrder: number,
  chapterNumber: number
): VerseSpan[] | undefined {
  const spans = rawSpansFor(bookOrder, chapterNumber);
  if (!spans) return undefined;
  return spans.map(([start, end, text]) => ({ start, end, text }));
}

/**
 * The same chapter as a flat verse list, for the single-language reader.
 *
 * A merged range becomes ONE entry carrying both ends, so the reader can
 * print "39-40". It deliberately does not expand a range into one entry
 * per verse number: the translation has a single piece of text for the
 * whole range, so duplicating it under each number would misrepresent
 * the translation and would make a shared verse quote wrong.
 */
export function getTeluguVerses(
  bookOrder: number,
  chapterNumber: number
): BibleVerse[] | undefined {
  const spans = rawSpansFor(bookOrder, chapterNumber);
  if (!spans) return undefined;
  return spans.map(([start, end, text]) =>
    end > start ? { number: start, endNumber: end, text } : { number: start, text }
  );
}
