/**
 * The real Telugu Indian Revised Version (IRV) 2019 verse-text dataset --
 * resolves the Telugu half of the Bible sourcing gap documented in
 * /BIBLE_LICENSING.md. See that file's "Telugu -- resolved" section for
 * the full license/provenance writeup; summarized here:
 *
 *   - Source: BibleNLP/ebible (https://github.com/BibleNLP/ebible), a
 *     mirror of eBible.org's translation corpus, `corpus/tel-tel2017.txt`
 *     (verse-per-line, aligned to `metadata/vref.txt`'s canonical
 *     reference list) -- fetched via direct HTTPS requests to
 *     raw.githubusercontent.com/BibleNLP/ebible/main/..., verbatim bytes,
 *     not summarized/regenerated by any AI tool.
 *   - License: confirmed via that same repository's
 *     `metadata/licences.tsv`, whose `tel2017` row states License Type
 *     `by-sa`, Version `4.0` (CC BY-SA 4.0,
 *     http://creativecommons.org/licenses/by-sa/4.0/), Copyright Holder
 *     "Bridge Connectivity Solutions", translation "ఇండియన్ రివైజ్డ్
 *     వెర్షన్ (IRV) - తెలుగు -2019" (Indian Revised Version (IRV) --
 *     Telugu -- 2019), copyright (c) 2017, 2019. This is a structured,
 *     third-party-maintained metadata record naming the copyright holder
 *     and exact license by name+version, not an inference from a dataset
 *     field or an assumption of "public domain" -- see
 *     /BIBLE_LICENSING.md for why that distinction mattered here.
 *   - CC BY-SA 4.0 permits redistribution and adaptation (including the
 *     mechanical, text-preserving chapter/verse remapping described
 *     below), conditioned on attribution and ShareAlike -- both satisfied
 *     by this file's attribution above/in BIBLE_LICENSING.md and by this
 *     app remaining open about its own licensing.
 *
 * VERSIFICATION REMAPPING: `vref.txt` (and therefore the raw corpus line
 * order) uses the Hebrew/"original" versification for Joel and Malachi,
 * which splits differently from the standard English versification
 * books.ts already uses (matching the WEB dataset): Hebrew Joel has 4
 * chapters (English 3); Hebrew Malachi runs its 4th chapter's content
 * into chapter 3 (English keeps a distinct chapter 4). The import script
 * mechanically remapped references (Hebrew Joel 3:1-5 -> English
 * 2:28-32; Hebrew Joel 4:1-21 -> English 3:1-21; Hebrew Malachi 3:19-24
 * -> English 4:1-6) -- text-preserving, not reworded or reordered beyond
 * the chapter/verse label itself. This is a well-documented, standard
 * versification difference between traditions, not a data error.
 *
 * COMPLETENESS: 1187 of 1189 chapters have real, non-empty verse text.
 * The two exceptions -- Joel (English) chapter 3 and Malachi (English)
 * chapter 4 -- are verifiably empty in the raw source text itself at
 * every one of their expected reference lines (checked directly, not
 * assumed), not a transformation bug. Since ebible.org's own site
 * (which might hold the original USFM confirming why) is unreachable
 * from this development environment, whether this reflects a genuine
 * gap in the IRV 2019 translation or an extraction artifact on
 * BibleNLP's part could not be independently confirmed -- so, per
 * /BIBLE_LICENSING.md's "no fabricated content" rule, those two chapters
 * fall back to the existing, clearly-labeled synthetic placeholder
 * (isPlaceholder: true) via dataSource.ts, rather than being silently
 * left empty or invented. All other 1187 chapters -- 30,868 real
 * verses -- are genuine IRV 2019 text.
 *
 * VERSE COMBINING: unlike the WEB English dataset (implicit sequential
 * verse numbering), this translation legitimately combines some verses
 * under one printed verse number (translator's discretion, not a data
 * gap -- confirmed by cross-checking every chapter's verse-number set
 * against the already-validated WEB dataset: every non-matching chapter
 * has no verse number below its own maximum missing, i.e. no true
 * mid-chapter holes, only combined numbering at the high end of some
 * verses). So ./data/web-te.json stores EXPLICIT [verseNumber, text]
 * pairs per chapter, not an implicit index+1 array like web-en.json --
 * this preserves the translation's actual verse numbering instead of
 * mislabeling combined verses.
 *
 * ./data/web-te.json is keyed by [bookOrder as string][chapterNumber as
 * string] -> Array<[verseNumber: number, text: string]>. bookOrder
 * matches books.ts's `order` field exactly (1 = Genesis .. 66 =
 * Revelation).
 */
import teluguData from './data/web-te.json';
import type { BibleVerse } from './types';

type TeluguBibleData = Record<string, Record<string, [number, string][]>>;

const DATA = teluguData as unknown as TeluguBibleData;

/**
 * Returns the real Telugu IRV 2019 verses for a book/chapter, or
 * undefined if this dataset has no entry for it -- true for every valid
 * book/chapter except the two documented gap chapters above (Joel 3,
 * Malachi 4), which dataSource.ts falls back to placeholder for.
 */
export function getTeluguVerses(
  bookOrder: number,
  chapterNumber: number
): BibleVerse[] | undefined {
  const pairs = DATA[String(bookOrder)]?.[String(chapterNumber)];
  if (!pairs || pairs.length === 0) return undefined;
  return pairs.map(([number, text]) => ({ number, text }));
}
