/**
 * The real Telugu Indian Revised Version (IRV) 2019 verse-text dataset --
 * resolves the Telugu half of the Bible sourcing gap documented in
 * /BIBLE_LICENSING.md. See that file's "Telugu -- resolved" section for
 * the full license/provenance writeup; summarized here:
 *
 *   - Source: BibleNLP/ebible (https://github.com/BibleNLP/ebible), a
 *     mirror of eBible.org's translation corpus, `corpus/tel-tel2017.txt`
 *     (verse-per-line, aligned to `metadata/vref.txt`'s canonical
 *     reference list) -- fetched via direct HTTPS requests to
 *     raw.githubusercontent.com/BibleNLP/ebible/main/..., verbatim bytes,
 *     not summarized/regenerated by any AI tool.
 *   - License: confirmed via that same repository's
 *     `metadata/licences.tsv`, whose `tel2017` row states License Type
 *     `by-sa`, Version `4.0` (CC BY-SA 4.0,
 *     http://creativecommons.org/licenses/by-sa/4.0/), Copyright Holder
 *     "Bridge Connectivity Solutions", translation "ఇండియన్ రివైజ్డ్
 *     వెర్షన్ (IRV) - తెలుగు -2019" (Indian Revised Version (IRV) --
 *     Telugu -- 2019), copyright (c) 2017, 2019. This is a structured,
 *     third-party-maintained metadata record naming the copyright holder
 *     and exact license by name+version, not an inference from a dataset
 *     field or an assumption of "public domain" -- see
 *     /BIBLE_LICENSING.md for why that distinction mattered here.
 *   - CC BY-SA 4.0 permits redistribution and adaptation (including the
 *     mechanical, text-preserving chapter/verse remapping described
 *     below), conditioned on attribution and ShareAlike -- both satisfied
 *     by this file's attribution above/in BIBLE_LICENSING.md and by this
 *     app remaining open about its own licensing.
 *
 * VERSIFICATION REMAPPING: `vref.txt` (and therefore the raw corpus line
 * order) uses the Hebrew/"original" versification for Joel and Malachi,
 * which splits differently from the standard English versification
 * books.ts already uses (matching the WEB dataset): Hebrew Joel has 4
 * chapters (English 3); Hebrew Malachi runs its 4th chapter's content
 * into chapter 3 (English keeps a distinct chapter 4). The import script
 * mechanically remapped references (Hebrew Joel 3:1-5 -> English
 * 2:28-32; Hebrew Joel 4:1-21 -> English 3:1-21; Hebrew Malachi 3:19-24
 * -> English 4:1-6) -- text-preserving, not reworded or reordered beyond
 * the chapter/verse label itself. This is a well-documented, standard
 * versification difference between traditions, not a data error.
 *
 * COMPLETENESS: 1187 of 1189 chapters have real, non-empty verse text.
 * The two exceptions -- Joel (English) chapter 3 and Malachi (English)
 * chapter 4 -- were investigated exhaustively (not accepted at face
 * value) before being treated as a genuine, unrecoverable-from-here gap
 * rather than a mapping error:
 *   1. Byte-level: the full BibleNLP/ebible repository was cloned
 *      (not just individual raw files) and every one of the 27 expected
 *      lines (Joel Hebrew-ch.4:1-21, Malachi Hebrew-ch.3:19-24) is
 *      exactly 1 byte (a bare newline) in `corpus/tel-tel2017.txt` --
 *      confirmed directly, not inferred.
 *   2. Structural: `metadata/vref.txt` (the reference list this corpus
 *      is aligned to) has NO other entry anywhere that could hold this
 *      content under a different numbering -- there is no "MAL 4:x" row
 *      at all (Hebrew Malachi has only 3 chapters), and the "JOL 4:x"
 *      rows that do exist are exactly the 21 blank lines above. The
 *      versification remapping applied elsewhere in this file (see
 *      above) is therefore already the correct, complete mapping --
 *      there is nowhere else in this specific source file for this
 *      content to be hiding.
 *   3. Documentary: the repository's own README states plainly, under
 *      "Missing Verses": "Blank lines in the Bible text file indicate
 *      that the verse was not part of the source Bible." This is the
 *      extraction pipeline's own direct claim (via SIL's
 *      `bulk_extract_corpora.py`, which uses the `machine` library's
 *      standard versification-mapping tables, not naive positional
 *      alignment) -- not a guess about what a blank line might mean.
 *   4. Root-cause evidence: `metadata/licenses/tel-tel2017-copr.htm`
 *      (eBible.org's own generated copyright/status page for this exact
 *      publication, source files dated 29 Jan 2022) lists this
 *      translation's status as "Stage 5 - Further Quality Checking --
 *      In Progress" (stages 1-4 complete). A translation whose final QA
 *      pass was still in progress at the time this edition was
 *      published is a credible, sourced explanation for isolated
 *      missing chapters in an otherwise complete 66-book translation --
 *      not this app's error, and not evidence of a better mapping being
 *      available.
 * `ebible.org` itself (which might have since completed Stage 5 and
 * published newer, complete source files) remains unreachable from
 * every development environment this project has had access to, so
 * this could not be checked directly. Per /BIBLE_LICENSING.md's "no
 * fabricated content" rule, this text was NOT reconstructed, guessed,
 * or substituted from another translation. Those two chapters fall back
 * to the existing, clearly-labeled synthetic placeholder
 * (isPlaceholder: true) via dataSource.ts. This is a known,
 * intentionally NOT-yet-satisfied requirement, not a resolved one --
 * see `__tests__/teluguBible.test.ts`'s strict, exception-free
 * completeness test, which is committed deliberately failing for
 * exactly these two chapters rather than weakened to pass. All other
 * 1187 chapters -- 30,868 real verses -- are genuine IRV 2019 text.
 *
 * VERSE COMBINING: unlike the WEB English dataset (implicit sequential
 * verse numbering), this translation legitimately combines some verses
 * under one printed verse number (translator's discretion, not a data
 * gap -- confirmed by cross-checking every chapter's verse-number set
 * against the already-validated WEB dataset: every non-matching chapter
 * has no verse number below its own maximum missing, i.e. no true
 * mid-chapter holes, only combined numbering at the high end of some
 * verses). So ./data/web-te.json stores EXPLICIT [verseNumber, text]
 * pairs per chapter, not an implicit index+1 array like web-en.json --
 * this preserves the translation's actual verse numbering instead of
 * mislabeling combined verses.
 *
 * ./data/web-te.json is keyed by [bookOrder as string][chapterNumber as
 * string] -> Array<[verseNumber: number, text: string]>. bookOrder
 * matches books.ts's `order` field exactly (1 = Genesis .. 66 =
 * Revelation).
 */
import teluguData from './data/web-te.json';
import type { BibleVerse } from './types';

type TeluguBibleData = Record<string, Record<string, [number, string][]>>;

const DATA = teluguData as unknown as TeluguBibleData;

/**
 * Returns the real Telugu IRV 2019 verses for a book/chapter, or
 * undefined if this dataset has no entry for it -- true for every valid
 * book/chapter except the two documented gap chapters above (Joel 3,
 * Malachi 4), which dataSource.ts falls back to placeholder for.
 */
export function getTeluguVerses(
  bookOrder: number,
  chapterNumber: number
): BibleVerse[] | undefined {
  const pairs = DATA[String(bookOrder)]?.[String(chapterNumber)];
  if (!pairs || pairs.length === 0) return undefined;
  return pairs.map(([number, text]) => ({ number, text }));
}
