/**
 * GENERATED by scripts/derive-versification.mjs — do not edit by hand.
 *
 * For every canonical chapter, whether English and Telugu may be paired
 * verse by verse. See that script's header for what each value means and
 * why this is derived from the bundled data rather than hand-listed.
 *
 * Regenerate after any Bible import:
 *   node scripts/derive-versification.mjs
 * Verify it is current (CI / pre-commit):
 *   node scripts/derive-versification.mjs --check
 */

/** How a chapter's two translations may be presented together. */
export type ChapterAlignment =
  /** Same verse numbers in both. Verse-by-verse pairing is safe. */
  | 'aligned'
  /** Verse sets differ (Hebrew vs English chapter division). Chapter-level only. */
  | 'divergent'
  /** No Telugu text exists for this chapter in the source. */
  | 'absent';

/** Keyed `${bookOrder}:${chapter}`. Absent keys are 'aligned'. */
export const CHAPTER_ALIGNMENT: Readonly<Record<string, ChapterAlignment>> = Object.freeze({
  '1:31': 'divergent',
  '2:8': 'divergent',
  '2:22': 'divergent',
  '3:6': 'divergent',
  '4:16': 'divergent',
  '4:29': 'divergent',
  '5:12': 'divergent',
  '5:22': 'divergent',
  '5:29': 'divergent',
  '9:23': 'divergent',
  '10:18': 'divergent',
  '11:4': 'divergent',
  '12:11': 'divergent',
  '13:6': 'divergent',
  '14:2': 'divergent',
  '14:14': 'divergent',
  '16:4': 'divergent',
  '16:7': 'divergent',
  '16:9': 'divergent',
  '18:41': 'divergent',
  '21:5': 'divergent',
  '22:6': 'divergent',
  '23:9': 'divergent',
  '23:64': 'divergent',
  '24:9': 'divergent',
  '26:20': 'divergent',
  '27:4': 'divergent',
  '27:5': 'divergent',
  '28:1': 'divergent',
  '28:11': 'divergent',
  '28:13': 'divergent',
  '29:2': 'divergent',
  '29:3': 'divergent',
  '32:1': 'divergent',
  '33:5': 'divergent',
  '34:1': 'divergent',
  '38:1': 'divergent',
  '39:4': 'absent',
  '44:19': 'divergent',
  '47:13': 'divergent',
  '64:1': 'divergent',
  '66:12': 'divergent',
});

/** Total canonical chapters covered by the derivation. */
export const TOTAL_CHAPTERS = 1189;

/** Chapters safe for verse-by-verse bilingual pairing. */
export const ALIGNED_CHAPTERS = 1147;

/** Chapters where the two traditions divide text differently. */
export const DIVERGENT_CHAPTERS = 41;

/** Chapters with no Telugu text in the source at all. */
export const ABSENT_CHAPTERS = 1;

/** Aligned chapters that nonetheless merge some verses into ranges. */
export const MERGED_RANGE_CHAPTERS = 63;

export function alignmentFor(bookOrder: number, chapter: number): ChapterAlignment {
  return CHAPTER_ALIGNMENT[`${bookOrder}:${chapter}`] ?? 'aligned';
}
