/**
 * The real World English Bible (WEB) verse-text dataset -- English's half
 * of the Day 8 sourcing gap documented in /BIBLE_LICENSING.md is now
 * resolved. See that file's "English -- resolved" section for the full
 * license/provenance writeup; summarized here:
 *
 *   - Source: scrollmapper/bible_databases, `2024` branch,
 *     `json/t_web.json` (https://github.com/scrollmapper/bible_databases),
 *     fetched via a direct HTTPS request to
 *     raw.githubusercontent.com/scrollmapper/bible_databases/2024/json/t_web.json
 *     -- verbatim bytes, not summarized/regenerated by any AI tool.
 *   - That repository's README states plainly: "All included Bible
 *     translations are in the public domain," matching
 *     /BIBLE_LICENSING.md's independently-researched conclusion that the
 *     World English Bible itself is public domain (ebible.org/web/).
 *     Two independent sources agreeing is why this is treated as safe to
 *     import, not either source alone.
 *   - Verified complete on import: all 66 books, exactly the chapter
 *     counts books.ts already declares (929 OT + 260 NT = 1189), no
 *     verse-numbering gaps, no empty verses, 31,102 total verses (the
 *     well-known WEB verse count).
 * - Cleaning applied: WEB's inline translator footnotes (curly-brace
 *   asides like "{After \"God,\" the Hebrew has...}") are stripped for
 *   plain-reading display -- they're translator annotations, not part of
 *   the base translated verse text, and this app has no footnote-display
 *   UI to render them meaningfully. The verse text itself is otherwise
 *   unmodified from the source.
 *
 * ./data/web-en.json is keyed by [bookOrder as string][chapterNumber as
 * string] -> string[] (verse text, index 0 = verse 1, contiguous -- see
 * this file's own import validation, and dataSource.ts's use of it).
 * bookOrder matches books.ts's `order` field exactly (1 = Genesis .. 66 =
 * Revelation), which is also the scrollmapper dataset's own book-number
 * column, so no id-remapping table is needed.
 */
import webData from './data/web-en.json';

type WebBibleData = Record<string, Record<string, string[]>>;

const DATA = webData as unknown as WebBibleData;

/**
 * Returns the real WEB verse text for a book/chapter, or undefined if
 * this dataset has no entry for it (shouldn't happen for any valid
 * book/chapter per books.ts, given the completeness check above -- but
 * dataSource.ts still treats undefined as "fall back to placeholder"
 * rather than asserting, so a future data revision can never crash the
 * reader).
 */
export function getWebVerseTexts(
  bookOrder: number,
  chapterNumber: number
): string[] | undefined {
  return DATA[String(bookOrder)]?.[String(chapterNumber)];
}
