/**
 * The real World English Bible (WEB) verse-text dataset -- English's half
 * of the Day 8 sourcing gap documented in /BIBLE_LICENSING.md is now
 * resolved. See that file's "English -- resolved" section for the full
 * license/provenance writeup; summarized here:
 *
 *   - Source: scrollmapper/bible_databases, `2024` branch,
 *     `json/t_web.json` (https://github.com/scrollmapper/bible_databases),
 *     fetched via a direct HTTPS request to
 *     raw.githubusercontent.com/scrollmapper/bible_databases/2024/json/t_web.json
 *     -- verbatim bytes, not summarized/regenerated by any AI tool.
 *   - That repository's README states plainly: "All included Bible
 *     translations are in the public domain," matching
 *     /BIBLE_LICENSING.md's independently-researched conclusion that the
 *     World English Bible itself is public domain (ebible.org/web/).
 *     Two independent sources agreeing is why this is treated as safe to
 *     import, not either source alone.
 *   - Verified complete on import: all 66 books, exactly the chapter
 *     counts books.ts already declares (929 OT + 260 NT = 1189), no
 *     verse-numbering gaps, 31,102 total verses (the well-known WEB
 *     verse count).
 * - Cleaning applied, step 1: WEB's inline translator footnotes
 *   (curly-brace asides like "{After \"God,\" the Hebrew has...}") are
 *   stripped for plain-reading display -- they're translator
 *   annotations, not part of the base translated verse text, and this
 *   app has no footnote-display UI to render them meaningfully.
 * - Cleaning applied, step 2 (M4): the source's own JSON DOUBLE-ESCAPES
 *   its quotation marks, so every line of reported speech arrived
 *   carrying a literal backslash -- 7,213 of them across 4,503 verses,
 *   rendering on the page as `God said, \"Let there be light,\"` and
 *   travelling into whatever a member shared or copied. M4's visual QA
 *   is what finally put the corpus on screen in the real typeface and
 *   showed it. ONE backslash immediately preceding a double quote is
 *   removed and nothing else: a character-frequency comparison over all
 *   31,102 verses before and after differs in the backslash alone, so no
 *   word, no punctuation and no verse count changed. The World English
 *   Bible contains no backslashes; this was never scripture.
 *   ./__tests__/webBible.test.ts is what keeps the corpus clean.
 * - SEVEN verses are legitimately empty -- Luke 17:36, Acts 8:37, 15:34,
 *   24:7 and Romans 16:25-27 -- whose entire content in the source is a
 *   note that the manuscripts this translation follows do not contain
 *   the verse. The number is real and the text does not exist, so the
 *   reader prints the number and says the verse is not in this
 *   translation rather than leaving a blank line (see
 *   ./reader/ScriptureBody.tsx). Nothing is invented to fill them.
 *   The verse text is otherwise unmodified from the source.
 *
 * ./data/web-en.json is keyed by [bookOrder as string][chapterNumber as
 * string] -> string[] (verse text, index 0 = verse 1, contiguous -- see
 * this file's own import validation, and dataSource.ts's use of it).
 * bookOrder matches books.ts's `order` field exactly (1 = Genesis .. 66 =
 * Revelation), which is also the scrollmapper dataset's own book-number
 * column, so no id-remapping table is needed.
 */
import webData from './data/web-en.json';

type WebBibleData = Record<string, Record<string, string[]>>;

const DATA = webData as unknown as WebBibleData;

/**
 * Returns the real WEB verse text for a book/chapter, or undefined if
 * this dataset has no entry for it (shouldn't happen for any valid
 * book/chapter per books.ts, given the completeness check above -- but
 * dataSource.ts still treats undefined as "fall back to placeholder"
 * rather than asserting, so a future data revision can never crash the
 * reader).
 */
export function getWebVerseTexts(
  bookOrder: number,
  chapterNumber: number
): string[] | undefined {
  return DATA[String(bookOrder)]?.[String(chapterNumber)];
}
