import { readFileSync } from 'fs';
import { join } from 'path';
import { BIBLE_BOOKS, getBookById } from '../../bible/books';
import { getChapter } from '../../bible/dataSource';

/**
 * The admin dashboard's generated verse-count table, checked against the
 * corpus it was derived from.
 *
 * WHY THIS TEST LIVES HERE. The admin dashboard validates pool references
 * ("does John 3:99 exist?") from
 * admin/src/features/daily-verses/bibleStructure.ts, a table generated by
 * scripts/derive-bible-structure.mjs. The corpus it is derived from is
 * bundled in THIS package, so this is the only place the table can be
 * checked against the truth rather than against itself.
 *
 * What a failure means: someone re-imported a Bible, or hand-edited a
 * generated file. Re-run the generator.
 */
const STRUCTURE_PATH = join(
  __dirname,
  '../../../../../admin/src/features/daily-verses/bibleStructure.ts'
);

interface Row {
  id: string;
  name: string;
  order: number;
  verseCounts: number[];
}

function parseStructure(): Row[] {
  const source = readFileSync(STRUCTURE_PATH, 'utf8');
  const rows: Row[] = [];
  const entry =
    /\{ id: '([^']+)', name: '((?:[^'\\]|\\')+)', order: (\d+), verseCounts: \[([^\]]+)\] \}/g;
  let match: RegExpExecArray | null;
  while ((match = entry.exec(source)) !== null) {
    rows.push({
      id: match[1]!,
      name: match[2]!.replace(/\\'/g, "'"),
      order: Number(match[3]),
      verseCounts: match[4]!.split(',').map((n) => Number(n.trim())),
    });
  }
  return rows;
}

const STRUCTURE = parseStructure();

describe("the admin's generated Bible structure", () => {
  it('covers all 66 books, in canonical order, with the app’s own ids and names', () => {
    expect(STRUCTURE).toHaveLength(66);
    expect(STRUCTURE.map((row) => row.id)).toEqual(BIBLE_BOOKS.map((book) => book.id));
    expect(STRUCTURE.map((row) => row.name)).toEqual(
      BIBLE_BOOKS.map((book) => book.name)
    );
    expect(STRUCTURE.map((row) => row.order)).toEqual(
      BIBLE_BOOKS.map((book) => book.order)
    );
  });

  it('has one verse count per chapter of every book', () => {
    for (const row of STRUCTURE) {
      expect(row.verseCounts).toHaveLength(getBookById(row.id)!.chapterCount);
    }
  });

  it('matches the bundled corpus verse for verse', () => {
    // The whole point: if this drifts, the admin dashboard starts
    // accepting a reference the app cannot resolve, and that day's verse
    // silently becomes the fallback.
    const mismatches: string[] = [];
    for (const row of STRUCTURE) {
      row.verseCounts.forEach((count, index) => {
        const chapter = getChapter(row.id, index + 1, 'en');
        const actual = chapter?.verses.length ?? 0;
        if (actual !== count) {
          mismatches.push(`${row.name} ${index + 1}: table ${count}, corpus ${actual}`);
        }
      });
    }
    expect(mismatches.slice(0, 5)).toEqual([]);
    expect(mismatches).toHaveLength(0);
  });

  it('accounts for all 31,102 verses of the canon', () => {
    const total = STRUCTURE.reduce(
      (sum, row) => sum + row.verseCounts.reduce((n, count) => n + count, 0),
      0
    );
    expect(total).toBe(31102);
  });

  it('contains no verse TEXT -- only structure', () => {
    // A guard against someone "helpfully" inlining the Bible into the
    // admin bundle: 31,102 verses in Firestore or in a web bundle is the
    // thing M5 is built to avoid.
    const source = readFileSync(STRUCTURE_PATH, 'utf8');
    expect(source).not.toContain('For God so loved');
    expect(source).not.toContain('In the beginning');
    // Comfortably under 20 KB; the corpus is 8 MB.
    expect(source.length).toBeLessThan(20_000);
  });
});
