import { describe, expect, it } from 'vitest';
// Read as raw text through Vite rather than with `fs`, for the same
// reason ./votdSelection.test.ts does: this package's TypeScript is
// deliberately browser-only (tsconfig.app.json's `types: ["vite/client"]`),
// and pulling in Node's types to read one file would weaken that
// boundary for every file in the package.
import mobileCopy from '../../../../../mobile/src/features/daily-verses/votdYear.ts?raw';
import ownCopy from '../votdYear.ts?raw';
import { VOTD_YEAR, VOTD_YEAR_CONFIG, VOTD_YEAR_LENGTH, bundledVerseYear } from '../votdYear';
import { prepareVersePool, selectVerseForDate } from '../votdSelection';
import { addDays } from '../votdDate';

/**
 * THE SECOND CROSS-PACKAGE GUARD.
 *
 * ./votdSelection.test.ts pins the ALGORITHM against the mobile app's.
 * This pins the DATA. Both matter, and for the same reason: this
 * dashboard shows a pastor a year's schedule, and a schedule computed
 * from a different list of verses than the phone carries is not a
 * preview, it is fiction.
 *
 * The two copies are written by one generator
 * (scripts/derive-votd-year.mjs) into both packages, byte for byte
 * identical -- which is exactly what this file checks, rather than
 * spot-checking a few entries. The generated module has no imports for
 * this reason.
 */
describe('the built-in year', () => {
  it('is byte for byte the file the app carries', () => {
    // Not "equivalent". Identical -- it is one generated file written
    // to two places, and anything else means somebody edited a copy.
    expect(ownCopy).toBe(mobileCopy);
  });

  it('says in its own header that it is generated', () => {
    expect(ownCopy).toContain('GENERATED by scripts/derive-votd-year.mjs');
  });

  it('holds 365 references, and nothing but references', () => {
    expect(VOTD_YEAR_LENGTH).toBe(365);
    expect(VOTD_YEAR).toHaveLength(365);
    for (const entry of VOTD_YEAR) {
      expect(Object.keys(entry).sort()).toEqual([
        'active',
        'bookId',
        'chapter',
        'id',
        'order',
        'reference',
        'verse',
      ]);
    }
  });

  it('carries no duplicate, so the year really is 365 days long', () => {
    expect(prepareVersePool(bundledVerseYear())).toHaveLength(365);
  });

  it('is rotated with a fixed configuration, not the church’s seed', () => {
    // A phone with no signal has never read the settings document, so
    // the fallback cannot depend on it.
    expect(VOTD_YEAR_CONFIG).toEqual({
      enabled: true,
      seed: 'maranatha-fallback',
      poolVersion: 1,
    });
  });

  it('gives a different verse on all 365 consecutive days', () => {
    const pool = bundledVerseYear();
    const seen = new Set<string>();
    let date = '2026-01-01';
    for (let day = 0; day < 365; day += 1) {
      seen.add(selectVerseForDate(date, VOTD_YEAR_CONFIG, pool)!.reference);
      date = addDays(date, 1)!;
    }
    expect(seen.size).toBe(365);
  });
});
